[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"
name = "cv-aas"
version = "0.5.0"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
async-graphql = "2.5.4"
async-graphql-actix-web = "2.5.4"
env_logger = "0.8.3"
serde = {version = "1.0.123", features = ["derive"]}
serde_json = "1.0.62"
thiserror = "1.0.23"
