[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"
name = "cv-aas"
version = "0.3.0"

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
env_logger = "0.7.1"
juniper = "0.14.2"
serde = {version = "1.0.114", features = ["derive"]}
serde_json = "1.0.57"
thiserror = "1.0.20"
