[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"
name = "cv-aas"
version = "0.3.1"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.2.0"
env_logger = "0.8.1"
juniper = "0.14.2"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
thiserror = "1.0.21"
