[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"
name = "cv-aas"
version = "0.6.3"

[dependencies]
async-graphql = "2.9.10"
async-graphql-axum = "2.9.10"
axum = "0.2.3"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
thiserror = "1.0.26"
tokio = { version = "1.11.0", features = ["full"] }
tower = { version = "0.4.8", features = ["util", "timeout"] }
tower-http = { version = "0.1.1", features = ["full"] }
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
