[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2021"
name = "cv-aas"
version = "0.8.0"

[dependencies]
async-graphql = "2.10.2"
async-graphql-axum = "2.10.2"
axum = "0.2.8"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
thiserror = "1.0.30"
tokio = { version = "1.12.0", features = ["full"] }
tower = { version = "0.4.8", features = ["util", "timeout"] }
tower-http = { version = "0.1.1", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
