[package]
name = "cv-aas"
version = "0.1.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
thiserror = "1.0.20"
actix-web = "2.0.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
juniper = "0.14.2"
