[package]
name = "cv-aas"
version = "0.1.0"
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_dhall = "0.5.3"
serde_json = "1.0"
juniper = "0.14"
