[package]
authors = ["Sondre Nilsen <nilsen.sondre@gmail.com>"]
edition = "2018"
name = "cv-aas"
version = "0.4.0"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.2.0"
async-graphql = "2.5"
async-graphql-actix-web = "2.5"
env_logger = "0.8.1"
serde = {version = "1.0.117", features = ["derive"]}
serde_json = "1.0.59"
thiserror = "1.0.21"
