name: deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd lesebot
            ./deploy.sh
